### ISSUE TITLE
Multiple masks on same form only first works.

### ISSUE THREAD

**Issue by airboss001** [MaximBalaganskiy/aurelia-inputmask#2]
Found another issue.
When I have multiple masks on an dialog I am masking it appears that only the first one is being initialized and used correctly.

If I remove the other inputs and test them one by one they work correctly so seems there is something being used statically/globally in the attribute versus per input instance.

Looking to see if I can figure it out.

**Comment by airboss001** [comment]
The error is caused by the first issue where the label is not found.
Every mask after the first error is apparently ignored due to that.
I locally modified the source to remove the check for label and it works for all masks now.

I'll put a PR for it together.

**Comment by MaximBalaganskiy** [comment]
Fixed via 1e20275fbfeb4288f0c44389fd40736c0803b5dd
